### ISSUE TITLE
tag a release?

### ISSUE THREAD

**Issue by ghost** [schanzen/libgabe#4]
Is there any chance you can tag a release (possibly after the patch I've just send here)?
Not having to point to a git without tags would be better for many package managers. with git it kind of works, but I still prefer archives.

I'm working on pkgsrc packages for libgabe and other packages for reclaimid, gnunet.

**Comment by schanzen** [comment]
I can. Please note that GNUnet no longer depends on this library in git head (>0.11.3).

**Comment by schanzen** [comment]
v1.0 tagged

**Comment by ghost** [comment]
I've noticed that but thought it remained somewhere.
I don't know much of reclaim:id yet, so I assumed that this still remains somewhere in the dependency graph, but it seems as if both dependencies you removed a while back are no longer necessary for anything on your side?

**Comment by schanzen** [comment]
Basically, re:claimID (or better: src/reclaim) no longer depends on libgabe.
However, src/abe still needs libgabe. However, src/abe ist currently no longer needed by any other subsystem.

**Comment by ghost** [comment]
thanks!
